# Generated by Django 6.1.1 on 2026-10-03 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('Gmail', models.EmailField(max_length=254)),
                ('Mobile_No', models.IntegerField(max_length=10)),
                ('Username', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Address', models.TextField()),
                ('Product_Type', models.CharField(max_length=15)),
                ('Product_Name', models.CharField(max_length=15)),
                ('Apply_Coupon', models.CharField(max_length=10)),
            ],
        ),
    ]
