# Generated by Django 6.1.1 on 2026-10-03 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shinobiapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Mobile_No',
            field=models.IntegerField(),
        ),
    ]
